// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    daily_trips: {
        name: "daily_trips";
        parameters: {
          /** INT - use sql.int() */
          min_distance: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          pickup_date: string;
          /** @sqlType BIGINT */
          trips: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
        }>;
      };
  }
}
